### ISSUE TITLE
Access to the microbiome-chunyu s3 bucket is restricted

### ISSUE THREAD

**Issue by jacob-Iuo** [czbiohub/sc2-guide-InSilicoSCR#6]
Hello Dr. Zhao, I was curious if you are willing to provide the access information to the s3 links listed in the wiki. I was also curious whether the my_config.yml file listed in this wiki is the same as the config.yml file; I couldn't find this second config file anywhere on the repo.

**Comment by zhaoc1** [comment]
I updated the S3 bucket in the wiki document. Let me know you still can't access to it. 

And yes, my_config and config referred to the same config file.

**Comment by jacob-Iuo** [comment]
When I try to run this command on your updated s3 links, I get the following error message:

aws s3 cp s3://czhao-bucket/2020-sc2-inSilicoSCR/dbs/pathogen_strains_20200807 <destination path>
fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden

I also can't view the bucket contents in browser, perhaps due to read access permissions.

**Comment by zhaoc1** [comment]
There was a typo in the link: `aws s3 ls s3://czhao-bucket/2020-sc2-InSilicoSCR/dbs/`. This should work.

**Comment by jacob-Iuo** [comment]
![image](https://user-images.githubusercontent.com/63076089/113079481-f7ddfe00-9189-11eb-9dc2-5ccc299d615b.png)
Access is still denied for some reason

**Comment by zhaoc1** [comment]
Issue solved.
